/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author: Alberto Gil de la Fuente
 */
package anemiaDiagnosis;

unit ParametersUnit;

rule "AnemicSyndrome"
when
    $parameters : /parameters[hb < 8 && hb !=0, epo > 18.5, hematocrit < 53 , plaquets > 7.4, anysocytosis > 11.5 ,
    retyculocytes < 2.5, leucocytes > 4.5, rbc > 4.5 && rbc < 5.3, mcv > 80 && mcv < 100,
    mchc > 310 && mchc < 360, fe > 60 && fe < 170, bilirubine < 1.0 && bilirubine >= 0,
    ldh < 150 && ldh >= 0, haptoglobin > 41, ferritin > 12, b12 > 200, folicAcid > 2.7, glucocorticoids < 25 ,
    skinPalenes == true, tachycardia == true, tinnitus == true,
    palpitations == true, chestPain == true, infarction == true, dizziness == true, blurredVision == true,
    headAche == true, fatigue == true, musclePain == true, dyspnea == true, tachypnea == true, coldLimp == true]
then
    // IF I WANT TO DEBUG THE CODE, I CAN PRINT HERE WHATEVER I WANT System.out.println( op );
    //System.out.println( $patient + " has Anemic Syndrome. ");
    //$parameters.setAnemia(Anemia.ANEMIC_SYNDROME);

    modify ($parameters) { setAnemia(Anemia.ANEMIC_SYNDROME)}
    System.out.println($parameters.getAnemia());

end

rule "PosthemorrhagicAnemia"
when
    $parameters : /parameters[epo > 2.6 && epo < 18.5, hematocrit < 53 , plaquets > 7.4, anysocytosis > 11.5 ,leucocytes > 4.5,
    mcv > 80 && mcv < 100, bilirubine >= 0 && bilirubine < 1, ldh < 150 && ldh >= 0,
    haptoglobin > 41, ferritin > 12, b12 > 200, folicAcid > 2.7, glucocorticoids < 25, retyculocytes > 2.5 && retyculocytes != 0, bloodVolume == BloodVolume.DECREASED, rbc < 4.5, mchc < 310, fe < 60, skinPalenes == true,
    tachycardia == true, dizziness == true, fatigue == true, dyspnea == true, tachypnea == true,
    internHemorrage == true, externHemorrage == true]
then
    modify ($parameters) { setAnemia(Anemia.POSTHEMORRAGIC_ANEMIA)}
    System.out.println($parameters.getAnemia());



end

rule "HemolyticAnemia"
when
    $parameters : /parameters[hb > 8 && hb < 13.5, epo > 18.5, hematocrit < 53 , plaquets > 7.4,
    anysocytosis > 11.5 , leucocytes > 4.5,mcv > 80 && mcv < 100, mchc > 310 && mchc < 360,
    ferritin > 12, b12 > 200, folicAcid > 2.7, glucocorticoids < 25 , retyculocytes > 2.5, rbc > 5.9, mch > 32,
    hbUrine == true, feUrine == true, fe > 170, bilirubine >= 0 && bilirubine < 1, ldh >150, haptoglobin < 41, skinPalenes == true,
    fatigue == true, jaundice == true, splenomegalia == true, cranealBallooning == true, aplasticCrisis == true]
then
    modify ($parameters) { setAnemia(Anemia.HEMOLYTIC_ANEMIA)}
    System.out.println($parameters.getAnemia());

end

rule "InheritedSpherocytosis"
when
    $parameters : /parameters[hematocrit < 53 , plaquets > 7.4, anysocytosis > 11.5 , leucocytes > 4.5,
     rbc > 4.5 && rbc < 5.3, fe > 60 && fe < 170, haptoglobin > 41, ferritin > 12,
     b12 > 200, folicAcid > 2.7, glucocorticoids < 25 , retyculocytes > 2.5 && retyculocytes != 0, mcv < 80, mchc < 310,
     bilirubine >= 0 && bilirubine < 1, ldh > 150, folicAcid > 2.7,
     splenomegalia == true, cranealBallooning == true,
     aplasticCrisis == true, bacterianInfection == true, osteoporosis == true, boneDeformation == true, maxilarBoneHyperplasia == true]
then
    modify ($parameters) { setAnemia(Anemia.HEREDITARY_SPHEROCYTOSIS)}
    System.out.println($parameters.getAnemia());

end

rule "Thalassemia"
when
    $parameters : /parameters[mcv < 80 && mcv != 0, mchc > 360,
    epo > 2.6 && epo < 18.5, hematocrit < 53 ,  plaquets > 7.4, anysocytosis > 11.5 ,
    retyculocytes < 2.5, leucocytes > 4.5,rbc > 4.5 && rbc < 5.3,
    fe > 60 && fe < 170, bilirubine < 1.0 && bilirubine >= 0,
    ldh < 150 && ldh >= 0, haptoglobin > 41, ferritin > 12, b12 > 200, folicAcid > 2.7, glucocorticoids < 25 ,
    skinPalenes == true, palpitations == true, headAche == true,
    fatigue == true, dyspnea == true, coldLimp == true, nausea == true, brittleNails == true, tongueInflamation == true]
then

    modify ($parameters) { setAnemia(Anemia.THALASSEMIA)}
    System.out.println($parameters.getAnemia());

end

rule "MegaloblasticAnemia"
when
    $parameters : /parameters[anysocytosis < 11.5 && anysocytosis != 0, mcv > 100, mchc > 360, b12 < 200, folicAcid < 2.7,
    epo > 2.6 && epo < 18.5, hematocrit < 53 ,  plaquets > 7.4, retyculocytes < 2.5, leucocytes > 4.5, rbc > 4.5 && rbc < 5.3,
    fe > 60 && fe < 170, bilirubine < 1.0 && bilirubine >= 0,
    ldh < 150 && ldh >= 0, haptoglobin > 41, ferritin > 12, glucocorticoids < 25, skinPalenes == true,
    fatigue == true, internHemorrage == true, externHemorrage == true, petechiae == true]
then

    modify ($parameters) { setAnemia(Anemia.MEGALOBLASTIC_ANEMIA)}
    System.out.println($parameters.getAnemia());

end

rule "AplasticAnemia"
when
    $parameters : /parameters[plaquets < 7.4 && plaquets !=0, leucocytes< 4.5, rbc < 4.5, epo > 2.6 && epo < 18.5, hematocrit < 53 , anysocytosis > 11.5 , retyculocytes < 2.5,
    mcv > 80 && mcv < 100, mchc > 310 && mchc < 360,
    fe > 60 && fe < 170, bilirubine < 1.0 && bilirubine >= 0, ldh < 150 && ldh >= 0, haptoglobin > 41, ferritin > 12,
    b12 > 200, folicAcid > 2.7, glucocorticoids < 25, skinPalenes == true, headAche == true,
    fatigue == true, dyspnea == true]
then
    modify ($parameters) { setAnemia(Anemia.APLASTIC_ANEMIA)}
    System.out.println($parameters.getAnemia());
end

rule "ChronicAnemia"
when
    $parameters : /parameters[epo < 2.6 && epo != 0, rbc > 5.9 ,mcv < 80, hematocrit < 53 ,
    plaquets > 7.4, anysocytosis > 11.5 , retyculocytes < 2.5, leucocytes > 4.5, mchc > 310 && mchc < 360,
    fe > 60 && fe < 170, bilirubine < 1.0 && bilirubine >= 0, ldh < 150 && ldh >= 0,
    haptoglobin > 41, ferritin > 12, b12 > 200, folicAcid > 2.7, glucocorticoids < 25,dizziness == true,
    brittleNails == true , headAche == true , dyspnea == true ,skinPalenes == true, fatigue == true]
then

    modify ($parameters) { setAnemia(Anemia.CHRONIC_ANEMIA)}
    System.out.println($parameters.getAnemia());

end

rule "Policythemia"
when
    $parameters : /parameters[hb > 17.5 && hb != 0, epo > 18.5, hematocrit > 53, plaquets > 10, leucocytes < 4.5 ,
    bloodVolume == BloodVolume.INCREASED, mcv > 100 ,glucocorticoids > 25,  anysocytosis > 11.5, retyculocytes < 2.5, rbc > 4.5 && rbc < 5.3,
    mchc > 310 && mchc < 360, fe > 60 && fe < 170, bilirubine < 1.0 && bilirubine >= 0,
    ldh < 150 && ldh >= 0, haptoglobin > 41, ferritin > 12, b12 > 200, folicAcid > 2.7,
    dizziness == true, blurredVision == true,
    headAche == true, fatigue == true, dyspnea == true]

then
    modify ($parameters) { setAnemia(Anemia.POLYCYTHEMIA)}
    System.out.println($parameters.getAnemia());
end

query Diagnose
    $parameters : /parameters[ anemia == Anemia.POLYCYTHEMIA] //en la consutla se busca los parametros cuya hemoglobina este por encima de 18.5
end
