package anemiaDiagnosis;

public enum Anemia {
    ANEMIC_SYNDROME, POSTHEMORRAGIC_ANEMIA, HEMOLYTIC_ANEMIA, HEREDITARY_SPHEROCYTOSIS,THALASSEMIA,IRON_DEFICIENCY_ANEMIA,MEGALOBLASTIC_ANEMIA,
    APLASTIC_ANEMIA,CHRONIC_ANEMIA, POLYCYTHEMIA,NONE
}
